version: '3'
services:
  mongodb:
    container_name: some-mongo
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    #    volumes:
    #      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  nginx:
    container_name: some-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    container_name: some-springappjar
    build:
      context: .
      dockerfile: Dockerfile
    #    image: springbootappjar
    #    restart: unless-stopped
    working_dir: /home
    command: java -jar SpringBootApp-0.0.1-SNAPSHOT.jar --spring.config.location=file:///home/config/application.properties
    volumes:
      - ./build/libs/SpringBootApp-0.0.1-SNAPSHOT.jar:/home/SpringBootApp-0.0.1-SNAPSHOT.jar
    expose:
      - "5000"
    depends_on:
      - mongodb